### ISSUE TITLE
UR5 code

### ISSUE THREAD

**Issue by seivazi** [kindredresearch/arp#1]
Could you share the code you use for experimenting with UR5?
In paper you mentioned about SenseAct repo. It would be great to see this example in addition to SenseAct repo.

**Comment by dkorenkevych** [comment]
The UR5 environment used in the experiments is defined in SenseAct, which was referenced in the paper: https://github.com/kindredresearch/SenseAct/blob/master/senseact/envs/ur/reacher_env.py.
The only modification was in the reward function, which was sparse in arp experiments. The learning code is identical to Mujoco example here (https://github.com/kindredresearch/arp/blob/master/examples/run_mujoco_ppo.py) with SenseAct UR5 environment used instead of Mujoco.
